### ISSUE TITLE
[SEOBundle] fieldtype metas default_pattern's values lost

### ISSUE THREAD

**Issue by rhidja** [Novactive/Nova-eZPlatform-Bundles#19]
Hello,

I set up a basic configuration

```
nova_ezseo:
    system:
        default:
            fieldtype_metas_identifier: "metas"
            fieldtype_metas:
                title:
                    label: 'Title'
                    default_pattern: "<title|name>"
                description:
                    label: 'Description'
                    default_pattern: "<description|short_description|title|name>"
                keywords:
                    label: 'Keywords'
                    default_pattern: ~
```
Whend i dump 

```
class NovaeZSEOExtension:

            $metasConfig = $this->configResolver->getParameter('fieldtype_metas', 'nova_ezseo');

            print '<pre>';
            print_r($metasConfig);
            print '</pre>';
```

I got this result:

```
Array
(
    [title] => Array
        (
            [label] => Title
            [default_pattern] => 
        )

    [description] => Array
        (
            [label] => Description
            [default_pattern] => 
        )

    [keywords] => Array
        (
            [label] => Keywords
            [default_pattern] => 
        )

)
```
All my pattern identifier are lost! Do you have any explanation please?

**Comment by Plopix** [comment]
Hello @rhidja,

Where do you run that code? Are you sure you don't have anything else set up.
It does work for me.
Which version of eZ?


```yaml
nova_ezseo:
    system:
        default:
            google_verification: plop2test42
            fieldtype_metas_identifier: "metas"
            default_metas:
                author: "eZ Community Bundle Nova eZ SEO Bundle"
                copyright: ~
                generator: "eZ Platform"
                MSSmartTagsPreventParsing: "TRUE"
            fieldtype_metas:
                title:
                    label: 'Title'
                    default_pattern: "<title|name>"
                description:
                    label: 'Description'
                    default_pattern: "<intro|description|short_description|title|name>"
                keywords:
                    label: 'Keywords'
                    default_pattern: "<title>"
                test:
                    label: 'Test'
                    default_pattern: "<image>"

```

In the front I can see

```html
<meta name="description" content="Hello Intro"/>
<meta name="keywords" content="Hello Title"/>
<meta name="test" content="https://127.0.0.1:11083/var/site/storage/images/_aliases/social_network_image/9/9/1/0/199-1-eng-GB/novabynextedia.png"/>
<title>Hello Title</title>
<link rel="canonical" href="https://127.0.0.1:11083/hello-short-title" />
```

and in a controller

```php
 $metasConfig = $configResolver->getParameter('fieldtype_metas', 'nova_ezseo');
dd($metasConfig);
```
![Screen Shot 2020-10-23 at 9 13 12 AM](https://user-images.githubusercontent.com/313532/97027718-fc81f480-150f-11eb-8da7-0d66cc865c54.png)
